### PR TITLE
V1.9 rc

### PR DESCRIPTION
**Pull request by mkosunen**

### CODE REVIEW

**Comment by mkosunen** [comment]
@Roenski @sporrasm @vlahtin @dc14830 To my understanding this is ready to be merged.

Major refactoring has been implemented both on RTL and spice. Could you please test there on your designs and report if something broke.  I'd like to finish the release befor 31.3.

Thanks.

**Comment by mkosunen** [comment]
Especially @sporrasm : I think concept of 'strobed' output is currently nonexistent. Should is still be there?

**Comment by vlahtin** [comment]
Looks to work fine for me.

**Review by vlahtin — APPROVED** [review]

**Review by dc14830 — APPROVED** [review]
Haven't encountered any issues with spectre sims

**Comment by vlahtin** [comment]
Actually, I may have found an issue, which is not related to my testbenches, but with testbenches with Santeri's naming convention. This goes back to the BAG/SyDeKick naming convention. I noticed that Santeri is naming TheSyDeKick entities as entity_sim, and BAG generators as entity_gen. 

It seems to me that this does not work, as spice/spice_module.py (lines 94-155), assume that the name of the SyDeKick root entity is the same as the Virtuoso cell name. This is something I just noticed, as I tried to create a testbench with Santeri's convention. Please confirm @sporrasm if this has work previously and does not now work. This may just be something wrong in my testbench, which is under development and newer has been simulated previously

ping @mkosunen 

EDIT: renaming the testbench by removing the _sim solved the issue, so it is related to the naming.

**Comment by mkosunen** [comment]
@sporrasm  can probably elaborate the naming convention. if the block name is 'block', the name of the generator is 'block_gen', and the entity name is 'block' 'block_sim' is against the default naming convention.

**Comment by mkosunen** [comment]
Followups of spice to [https://github.com/TheSystemDevelopmentKit/spice/pull/45](https://github.com/TheSystemDevelopmentKit/spice/pull/45)

**Pull request merged**
